// IP — Caramurú Construções — assinatura do autor

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (PostgreSQL) */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull Changes
         * @description Consistent tenant delta. V1 supports schema 1, without schema migrations.
         */
        get: operations["pull_changes_api_v1_sync_get"];
        put?: never;
        /**
         * Push Changes
         * @description Atomically apply a durable mutation batch; replay the same batch_id after network failure.
         */
        post: operations["push_changes_api_v1_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/aprs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Aprs */
        get: operations["list_aprs_api_v1_safety_aprs_get"];
        put?: never;
        /** Create Apr */
        post: operations["create_apr_api_v1_safety_aprs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/aprs/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Apr */
        get: operations["get_apr_api_v1_safety_aprs__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/aprs/{record_id}/signatures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Apr */
        post: operations["sign_apr_api_v1_safety_aprs__record_id__signatures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/aprs/{record_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Apr */
        post: operations["release_apr_api_v1_safety_aprs__record_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/permits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Permit */
        post: operations["create_permit_api_v1_safety_permits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/permits/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Permit */
        get: operations["get_permit_api_v1_safety_permits__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/permits/{record_id}/signatures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Permit */
        post: operations["sign_permit_api_v1_safety_permits__record_id__signatures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/safety/permits/{record_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Permit */
        post: operations["release_permit_api_v1_safety_permits__record_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload */
        post: operations["create_upload_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Upload Status */
        get: operations["upload_status_api_v1_uploads__upload_id__get"];
        put?: never;
        post?: never;
        /** Abort Upload */
        delete: operations["abort_upload_api_v1_uploads__upload_id__delete"];
        options?: never;
        head?: never;
        /** Upload Chunk */
        patch: operations["upload_chunk_api_v1_uploads__upload_id__patch"];
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Upload */
        post: operations["complete_upload_api_v1_uploads__upload_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @example ok
             */
            status: string;
            /**
             * Service
             * @default caramuru-api
             */
            service: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        JsonValue: unknown;
        /** MergeConflict */
        MergeConflict: {
            /**
             * Table Name
             * @enum {string}
             */
            table_name: "projects" | "assets" | "inspections" | "aprs";
            /**
             * Record Id
             * Format: uuid
             */
            record_id: string;
            /** Rejected Fields */
            rejected_fields: string[];
        };
        /** MutationMetadata */
        MutationMetadata: {
            /** Client Version */
            client_version: string;
            /** Changed Fields */
            changed_fields?: string[];
        };
        /** PermitInput */
        PermitInput: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Observation */
            observation: string;
            /** Voltage Kv */
            voltage_kv?: number | null;
            /** Work Height M */
            work_height_m?: number | null;
            /**
             * Risk Level
             * @default MEDIUM
             * @enum {string}
             */
            risk_level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Epi Checklist */
            epi_checklist?: {
                [key: string]: boolean;
            };
            /** Epc Checklist */
            epc_checklist?: {
                [key: string]: boolean;
            };
            /** Hazards */
            hazards?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid Until */
            valid_until?: string | null;
            /** Title */
            title: string;
            /** Activity */
            activity: string;
            /**
             * Apr Id
             * Format: uuid
             */
            apr_id: string;
        };
        /** PermitResponse */
        PermitResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Status */
            status: string;
            /** Requires Nr10 */
            requires_nr10: boolean;
            /** Requires Nr35 */
            requires_nr35: boolean;
            /** Voltage Kv */
            voltage_kv: number | null;
            /** Work Height M */
            work_height_m: number | null;
            /** Risk Level */
            risk_level: string;
            /** Epi Checklist */
            epi_checklist: {
                [key: string]: unknown;
            };
            /** Epc Checklist */
            epc_checklist: {
                [key: string]: unknown;
            };
            /** Hazards */
            hazards: unknown[];
            /** Tst Signature */
            tst_signature: {
                [key: string]: unknown;
            } | null;
            /** Encarregado Signature */
            encarregado_signature: {
                [key: string]: unknown;
            } | null;
            /** Valid From */
            valid_from: string | null;
            /** Valid Until */
            valid_until: string | null;
            /** Released At */
            released_at: string | null;
            /**
             * Apr Id
             * Format: uuid
             */
            apr_id: string;
            /** Title */
            title: string;
            /** Activity */
            activity: string;
        };
        /** PullResponse */
        PullResponse: {
            /** Changes */
            changes: {
                [key: string]: components["schemas"]["PullTableChanges"];
            };
            /** Timestamp */
            timestamp: number;
        };
        /** PullTableChanges */
        PullTableChanges: {
            /** Created */
            created?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Updated */
            updated?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Deleted */
            deleted?: string[];
        };
        /** PushRequest */
        PushRequest: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Last Pulled At */
            last_pulled_at: number;
            /** Changes */
            changes: {
                [key: string]: components["schemas"]["TableChanges"];
            };
            /** Metadata */
            metadata: {
                [key: string]: {
                    [key: string]: components["schemas"]["MutationMetadata"];
                };
            };
        };
        /** PushResponse */
        PushResponse: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Applied */
            applied: number;
            /** Conflicts */
            conflicts: components["schemas"]["MergeConflict"][];
            /**
             * Requires Pull
             * @default true
             */
            requires_pull: boolean;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** SafetyInput */
        SafetyInput: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Observation */
            observation: string;
            /** Voltage Kv */
            voltage_kv?: number | null;
            /** Work Height M */
            work_height_m?: number | null;
            /**
             * Risk Level
             * @default MEDIUM
             * @enum {string}
             */
            risk_level: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Epi Checklist */
            epi_checklist?: {
                [key: string]: boolean;
            };
            /** Epc Checklist */
            epc_checklist?: {
                [key: string]: boolean;
            };
            /** Hazards */
            hazards?: string[];
            /** Valid From */
            valid_from?: string | null;
            /** Valid Until */
            valid_until?: string | null;
        };
        /** SafetyResponse */
        SafetyResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Status */
            status: string;
            /** Requires Nr10 */
            requires_nr10: boolean;
            /** Requires Nr35 */
            requires_nr35: boolean;
            /** Voltage Kv */
            voltage_kv: number | null;
            /** Work Height M */
            work_height_m: number | null;
            /** Risk Level */
            risk_level: string;
            /** Epi Checklist */
            epi_checklist: {
                [key: string]: unknown;
            };
            /** Epc Checklist */
            epc_checklist: {
                [key: string]: unknown;
            };
            /** Hazards */
            hazards: unknown[];
            /** Tst Signature */
            tst_signature: {
                [key: string]: unknown;
            } | null;
            /** Encarregado Signature */
            encarregado_signature: {
                [key: string]: unknown;
            } | null;
            /** Valid From */
            valid_from: string | null;
            /** Valid Until */
            valid_until: string | null;
            /** Released At */
            released_at: string | null;
        };
        /** SignatureInput */
        SignatureInput: {
            /**
             * Signer Role
             * @enum {string}
             */
            signer_role: "TST" | "ENCARREGADO";
            /** Signature Svg */
            signature_svg: string;
            /** Sha256 */
            sha256: string;
            /**
             * Signed At
             * Format: date-time
             */
            signed_at: string;
        };
        /** TableChanges */
        TableChanges: {
            /** Created */
            created?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Updated */
            updated?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Deleted */
            deleted?: string[];
        };
        /** UploadCreate */
        UploadCreate: {
            /**
             * Photo Id
             * Format: uuid
             */
            photo_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Apr Id */
            apr_id?: string | null;
            /** Work Permit Id */
            work_permit_id?: string | null;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /**
             * Content Type
             * @default image/webp
             */
            content_type: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Accuracy M */
            accuracy_m: number;
            /**
             * Gnss Timestamp
             * Format: date-time
             */
            gnss_timestamp: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Watermark Text */
            watermark_text: string;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    pull_changes_api_v1_sync_get: {
        parameters: {
            query?: {
                last_pulled_at?: number;
                schema_version?: 1;
                migration?: "null" | null;
            };
            header: {
                "X-Tenant-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_changes_api_v1_sync_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_aprs_api_v1_safety_aprs_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header: {
                "X-Tenant-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_apr_api_v1_safety_aprs_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_apr_api_v1_safety_aprs__record_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_apr_api_v1_safety_aprs__record_id__signatures_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignatureInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_apr_api_v1_safety_aprs__record_id__release_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SafetyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_permit_api_v1_safety_permits_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermitInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_permit_api_v1_safety_permits__record_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_permit_api_v1_safety_permits__record_id__signatures_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignatureInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_permit_api_v1_safety_permits__record_id__release_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_api_v1_uploads_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_status_api_v1_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_upload_api_v1_uploads__upload_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_chunk_api_v1_uploads__upload_id__patch: {
        parameters: {
            query?: never;
            header: {
                "Upload-Offset": number;
                "X-Tenant-ID": string;
            };
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_api_v1_uploads__upload_id__complete_post: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-ID": string;
            };
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
