// IP — Caramurú Construções — assinatura do autor

"use client";

import { useEffect, useMemo, useState } from "react";
import { Badge, Button, Card, CardContent, CardHeader, ProgressBar, SectionTitle, cn } from "./ui";

type Role = "DIRETOR" | "ENGENHEIRO_RESIDENTE" | "TST" | "ENCARREGADO" | "FISCAL";
type Module = "overview" | "progress" | "rdo" | "assets";

const phases = ["Sondagem", "Fundação / Concretagem", "Içamento", "Encordoamento", "Comissionamento"];
const structures = Array.from({ length: 80 }, (_, i) => ({ id: i + 1, phase: phases[Math.min(4, Math.floor(i / 18))], progress: Math.min(100, 17 + i * 1.02), crew: 8 + (i % 9), updated: `${8 + (i % 5)}:${String((i * 7) % 60).padStart(2, "0")}` }));
const aprs = [
  { id: "APR-2026-081", title: "Içamento de pórtico SE Norte", owner: "TST Camila Rocha", status: "Aguardando aprovação", risk: "NR-35", color: "amber" as const, time: "há 18 min" },
  { id: "APR-2026-080", title: "Encordoamento LT — Torre 34", owner: "TST João Pires", status: "Liberada", risk: "NR-10 AT", color: "green" as const, time: "há 42 min" },
  { id: "APR-2026-079", title: "Concretagem de fundação T-31", owner: "TST Ana Lima", status: "Aguardando aprovação", risk: "EPC", color: "amber" as const, time: "há 1 h" },
];
const photos = [
  { title: "Frente de montagem — T-34", geo: "-23.550520, -46.633308", time: "10:42 UTC", status: "WebP verificado" },
  { title: "Aterramento temporário — SE Norte", geo: "-23.552101, -46.630921", time: "09:58 UTC", status: "WebP verificado" },
  { title: "EPI equipe de içamento", geo: "-23.547201, -46.636104", time: "09:16 UTC", status: "WebP verificado" },
];

const rolePermissions: Record<Module, Role[]> = {
  overview: ["DIRETOR", "ENGENHEIRO_RESIDENTE", "TST", "ENCARREGADO", "FISCAL"],
  progress: ["DIRETOR", "ENGENHEIRO_RESIDENTE", "TST", "ENCARREGADO", "FISCAL"],
  rdo: ["DIRETOR", "ENGENHEIRO_RESIDENTE", "TST", "ENCARREGADO", "FISCAL"],
  assets: ["DIRETOR", "ENGENHEIRO_RESIDENTE", "TST", "ENCARREGADO"],
};

function roleLabel(role: Role) { return role.replace("_", " "); }

function Sidebar({ active, onChange, role }: { active: Module; onChange: (value: Module) => void; role: Role }) {
  const items: Array<{ id: Module; label: string; icon: string }> = [{ id: "overview", label: "Visão geral", icon: "⌂" }, { id: "progress", label: "Avanço físico", icon: "▥" }, { id: "rdo", label: "Diário de obras", icon: "☷" }, { id: "assets", label: "Ativos e etiquetas", icon: "▦" }];
  return <aside className="hidden min-h-screen w-72 shrink-0 flex-col border-r border-slate-200 bg-white px-5 py-6 dark:border-slate-800 dark:bg-slate-950 lg:flex">
    <div className="flex items-center gap-3 px-2"><div className="grid size-10 place-items-center rounded-xl bg-caramuru-gold font-black text-slate-950">C</div><div><p className="text-sm font-black tracking-tight text-slate-950 dark:text-white">CARAMURÚ</p><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">Engenharia de campo</p></div></div>
    <div className="mt-12"><p className="px-3 text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Workspace</p><nav className="mt-3 space-y-1">{items.map(item => <button key={item.id} onClick={() => rolePermissions[item.id].includes(role) && onChange(item.id)} className={cn("flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold transition", active === item.id ? "bg-slate-950 text-white shadow-lg shadow-slate-950/10 dark:bg-caramuru-gold dark:text-slate-950" : "text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-900", !rolePermissions[item.id].includes(role) && "cursor-not-allowed opacity-40")}><span className="grid size-7 place-items-center rounded-lg bg-current/10 text-lg">{item.icon}</span>{item.label}</button>)}</nav></div>
    <div className="mt-auto rounded-2xl bg-slate-100 p-4 dark:bg-slate-900"><p className="text-xs font-black text-slate-950 dark:text-white">Obra ativa</p><p className="mt-1 text-sm font-bold text-slate-700 dark:text-slate-300">LT 230 kV — Vale do Sol</p><p className="mt-3 text-xs text-slate-500">Sincronizado há 2 min</p><div className="mt-2"><ProgressBar value={68} tone="green" /></div></div>
  </aside>;
}

function Topbar({ role, dark, onToggle }: { role: Role; dark: boolean; onToggle: () => void }) {
  return <header className="flex min-h-20 items-center justify-between gap-4 border-b border-slate-200 bg-white/80 px-5 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/80 sm:px-8"><div><p className="text-xs font-bold text-slate-400">TERÇA-FEIRA, 10 DE SETEMBRO DE 2026</p><h1 className="mt-1 text-lg font-black text-slate-950 dark:text-white">Centro de comando</h1></div><div className="flex items-center gap-2 sm:gap-4"><button onClick={onToggle} className="grid size-10 place-items-center rounded-xl border border-slate-200 text-lg text-slate-600 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800" aria-label="Alternar tema">{dark ? "☀" : "☾"}</button><div className="hidden h-8 w-px bg-slate-200 dark:bg-slate-700 sm:block" /><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-blue-100 text-sm font-black text-blue-800 dark:bg-blue-950 dark:text-blue-200">ER</div><div className="hidden sm:block"><p className="text-sm font-black text-slate-950 dark:text-white">Eng. Residente</p><p className="text-xs text-slate-500">{roleLabel(role)}</p></div></div></div></header>;
}

function Kpi({ label, value, detail, tone, icon }: { label: string; value: string; detail: string; tone: "gold" | "green" | "blue" | "red"; icon: string }) {
  return <Card className="relative overflow-hidden"><div className={cn("absolute right-0 top-0 h-1 w-full", tone === "gold" && "bg-caramuru-gold", tone === "green" && "bg-emerald-500", tone === "blue" && "bg-blue-500", tone === "red" && "bg-rose-500")} /><CardContent className="pt-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400">{label}</p><p className="mt-2 text-3xl font-black tracking-tight text-slate-950 dark:text-white">{value}</p><p className="mt-1 text-xs font-semibold text-slate-500 dark:text-slate-400">{detail}</p></div><span className="grid size-10 place-items-center rounded-xl bg-slate-100 text-xl dark:bg-slate-800">{icon}</span></div></CardContent></Card>;
}

function MapPanel() {
  const [zoom, setZoom] = useState(1);
  const [showTowers, setShowTowers] = useState(true);
  const [showSubstations, setShowSubstations] = useState(true);
  const towerPoints = Array.from({ length: 80 }, (_, i) => ({ x: 35 + i * 4.5, y: 205 - Math.sin(i / 7) * 42 - i * 0.8 }));
  return <Card className="overflow-hidden"><CardHeader><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Mapa operacional</p><h3 className="mt-1 text-lg font-black text-slate-950 dark:text-white">Traçado LT 230 kV — Vale do Sol</h3></div><Badge tone="blue">PostGIS · EPSG:4326</Badge></CardHeader><CardContent className="p-0"><div className="relative h-[330px] overflow-hidden bg-[#dce8e4] dark:bg-[#172a2e]" data-map-provider="maplibre"><div className="absolute inset-0 opacity-30" style={{ backgroundImage: "linear-gradient(#78958d 1px, transparent 1px), linear-gradient(90deg, #78958d 1px, transparent 1px)", backgroundSize: "38px 38px" }} /><svg viewBox="0 0 440 280" className="absolute inset-0 h-full w-full" role="img" aria-label="Mapa interativo do traçado da linha de transmissão" style={{ transform: `scale(${zoom})`, transformOrigin: "center" }}><path d="M 0 240 C 120 170, 180 250, 290 145 S 390 70, 440 18" fill="none" stroke="#89a59b" strokeWidth="34" opacity=".32" /><path d="M 0 240 C 120 170, 180 250, 290 145 S 390 70, 440 18" fill="none" stroke="#c4a35a" strokeWidth="3" strokeDasharray="8 5" />{showTowers && towerPoints.map((p, i) => <g key={i}><circle cx={p.x % 440} cy={p.y} r={i % 10 === 0 ? 4 : 2.2} fill={i < 54 ? "#126b5a" : "#c46732"} stroke="white" strokeWidth="1" /><title>Torre {i + 1} — {structures[i].phase}</title></g>)}{showSubstations && <><polygon points="38,48 93,33 108,62 51,78" fill="#2f65c8" opacity=".8" /><text x="42" y="29" fill="#1f3e76" fontSize="9" fontWeight="700">SE NORTE</text><polygon points="339,220 396,198 414,230 356,252" fill="#2f65c8" opacity=".8" /><text x="340" y="270" fill="#1f3e76" fontSize="9" fontWeight="700">SE SUL</text></>}</svg><div className="absolute bottom-4 left-4 flex flex-wrap gap-2"><button onClick={() => setShowTowers(!showTowers)} className={cn("rounded-lg px-3 py-2 text-xs font-black shadow", showTowers ? "bg-white text-slate-800" : "bg-slate-900 text-white")}>● Torres 1–80</button><button onClick={() => setShowSubstations(!showSubstations)} className={cn("rounded-lg px-3 py-2 text-xs font-black shadow", showSubstations ? "bg-white text-slate-800" : "bg-slate-900 text-white")}>▰ Subestações</button></div><div className="absolute right-4 top-4 flex flex-col overflow-hidden rounded-lg bg-white shadow"><button onClick={() => setZoom(value => Math.min(1.5, value + .1))} className="grid size-9 place-items-center text-lg font-black text-slate-700 hover:bg-slate-100">+</button><button onClick={() => setZoom(value => Math.max(.8, value - .1))} className="grid size-9 place-items-center border-t text-lg font-black text-slate-700 hover:bg-slate-100">−</button></div></div></CardContent></Card>;
}

function ProgressModule() {
  const [filter, setFilter] = useState("Todos");
  const visible = filter === "Todos" ? structures : structures.filter(item => item.phase === filter);
  return <div className="space-y-6"><SectionTitle eyebrow="Planejamento e produção" title="Avanço físico por estrutura" description="Acompanhe a liberação de cada torre e fase construtiva." action={<select value={filter} onChange={event => setFilter(event.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700 outline-none dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200"><option>Todos</option>{phases.map(phase => <option key={phase}>{phase}</option>)}</select>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Avanço geral" value="68%" detail="+4,8% nos últimos 7 dias" tone="gold" icon="↗" /><Kpi label="Torres liberadas" value="54 / 80" detail="67,5% do traçado" tone="green" icon="✓" /><Kpi label="Frentes ativas" value="12" detail="3 aguardando aprovação" tone="blue" icon="◈" /><Kpi label="Desvios críticos" value="02" detail="Requerem plano de ação" tone="red" icon="!" /></div><Card><CardHeader><div><h3 className="text-lg font-black text-slate-950 dark:text-white">Mapa e traçado</h3><p className="text-sm text-slate-500">Interaja com o traçado, torres e polígonos de subestação.</p></div></CardHeader><CardContent><MapPanel /></CardContent></Card><Card><CardHeader><div><h3 className="text-lg font-black text-slate-950 dark:text-white">Estruturas em campo</h3><p className="text-sm text-slate-500">{visible.length} registros visíveis · atualizado pelo sync mobile.</p></div><Badge tone="green">Ao vivo</Badge></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-400 dark:border-slate-700"><tr><th className="pb-3">Estrutura</th><th className="pb-3">Fase atual</th><th className="pb-3">Avanço</th><th className="pb-3">Efetivo</th><th className="pb-3">Última leitura</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{visible.slice(0, 18).map(item => <tr key={item.id}><td className="py-3 font-black text-slate-950 dark:text-white">Torre {item.id}</td><td className="py-3"><Badge tone={item.phase === "Comissionamento" ? "green" : item.phase === "Encordoamento" ? "blue" : "slate"}>{item.phase}</Badge></td><td className="w-52 py-3"><div className="flex items-center gap-3"><ProgressBar value={item.progress} tone={item.progress > 70 ? "green" : "gold"} /><span className="w-10 text-right text-xs font-bold text-slate-500">{Math.round(item.progress)}%</span></div></td><td className="py-3 font-semibold text-slate-600 dark:text-slate-300">{item.crew} pessoas</td><td className="py-3 text-slate-500">Hoje, {item.updated}</td></tr>)}</tbody></table></CardContent></Card></div>;
}

function OverviewModule({ onRdo }: { onRdo: () => void }) {
  return <div className="space-y-6"><SectionTitle eyebrow="Visão executiva" title="Bom dia, Engenheiro" description="O canteiro está operando com 12 frentes ativas." action={<Button onClick={onRdo}>Abrir diário de obras →</Button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Avanço físico" value="68%" detail="Meta do mês: 72%" tone="gold" icon="↗" /><Kpi label="Obra em campo" value="12 / 14" detail="frentes liberadas" tone="green" icon="⌁" /><Kpi label="APR pendentes" value="03" detail="2 de NR-35 · 1 de EPC" tone="blue" icon="⚠" /><Kpi label="Efetivo hoje" value="126" detail="+8 desde ontem" tone="green" icon="♙" /></div><div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><Card><CardHeader><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Produção</p><h3 className="mt-1 text-lg font-black text-slate-950 dark:text-white">Fases do empreendimento</h3></div><Badge tone="green">No ritmo</Badge></CardHeader><CardContent className="space-y-5">{phases.map((phase, index) => { const value = [100, 86, 70, 47, 21][index]; return <div key={phase}><div className="mb-2 flex items-center justify-between"><span className="text-sm font-bold text-slate-700 dark:text-slate-200">{phase}</span><span className="text-sm font-black text-slate-950 dark:text-white">{value}%</span></div><ProgressBar value={value} tone={index === 4 ? "blue" : index < 2 ? "green" : "gold"} /></div>; })}</CardContent></Card><Card><CardHeader><div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Segurança</p><h3 className="mt-1 text-lg font-black text-slate-950 dark:text-white">Pendências de aprovação</h3></div></CardHeader><CardContent className="space-y-3">{aprs.map(apr => <button key={apr.id} onClick={onRdo} className="w-full rounded-xl border border-slate-200 p-3 text-left hover:border-caramuru-gold dark:border-slate-700"><div className="flex items-center justify-between gap-2"><span className="text-xs font-black text-slate-500">{apr.id}</span><Badge tone={apr.color}>{apr.status === "Liberada" ? "Liberada" : "Pendente"}</Badge></div><p className="mt-2 text-sm font-bold text-slate-900 dark:text-white">{apr.title}</p><p className="mt-1 text-xs text-slate-500">{apr.owner} · {apr.time}</p></button>)}</CardContent></Card></div></div>;
}

function RdoModule({ role }: { role: Role }) {
  const [approved, setApproved] = useState<Record<string, boolean>>({});
  const canApprove = role === "DIRETOR" || role === "ENGENHEIRO_RESIDENTE";
  return <div className="space-y-6"><SectionTitle eyebrow="Diário de obra · RDO" title="O que está acontecendo no canteiro" description="Feed consolidado de segurança, clima, evidências e efetivo." action={<Button variant="secondary">Exportar RDO PDF</Button>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Clima" value="24° C" detail="Parcialmente nublado · vento 9 km/h" tone="blue" icon="☼" /><Kpi label="Efetivo em campo" value="126" detail="98% com ponto registrado" tone="green" icon="♙" /><Kpi label="APR abertas" value="03" detail="Aguardando decisão" tone="gold" icon="⚠" /><Kpi label="Fotos hoje" value="48" detail="Todas com GNSS e watermark" tone="green" icon="▧" /></div><div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><Card><CardHeader><div><h3 className="text-lg font-black text-slate-950 dark:text-white">Aprovação de frentes</h3><p className="text-sm text-slate-500">Decisões do Engenheiro Residente ficam auditadas.</p></div><Badge tone={canApprove ? "blue" : "slate"}>{canApprove ? "Pode aprovar" : "Somente leitura"}</Badge></CardHeader><CardContent className="space-y-3">{aprs.map(apr => <div key={apr.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-black text-slate-400">{apr.id}</p><p className="mt-1 font-black text-slate-950 dark:text-white">{apr.title}</p></div><Badge tone={approved[apr.id] ? "green" : apr.color}>{approved[apr.id] ? "Aprovada agora" : apr.status}</Badge></div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-slate-500">{apr.owner} · risco {apr.risk}</p>{canApprove && !approved[apr.id] && <div className="flex gap-2"><Button variant="secondary" className="min-h-9 px-3 text-xs">Rejeitar</Button><Button className="min-h-9 px-3 text-xs" onClick={() => setApproved(state => ({ ...state, [apr.id]: true }))}>Aprovar frente</Button></div>}</div></div>)}</CardContent></Card><Card><CardHeader><div><h3 className="text-lg font-black text-slate-950 dark:text-white">Evidências georreferenciadas</h3><p className="text-sm text-slate-500">Recebidas pelo pipeline antifraude mobile.</p></div><Badge tone="green">48 verificadas</Badge></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3 xl:grid-cols-1">{photos.map(photo => <div key={photo.title} className="flex gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div className="grid size-14 shrink-0 place-items-center rounded-lg bg-gradient-to-br from-slate-700 to-slate-400 text-2xl text-white">▧</div><div className="min-w-0"><p className="truncate text-sm font-black text-slate-950 dark:text-white">{photo.title}</p><p className="mt-1 text-xs text-slate-500">{photo.geo}</p><p className="mt-1 text-[11px] font-bold text-emerald-600">{photo.status} · {photo.time}</p></div></div>)}</CardContent></Card></div></div>;
}

function QrPattern({ seed }: { seed: string }) {
  const bits = Array.from({ length: 81 }, (_, i) => ((seed.charCodeAt(i % seed.length) + i * 17) % 5) < 2);
  return <svg viewBox="0 0 90 90" className="size-28 rounded bg-white p-2" aria-label={`QR ${seed}`}><rect width="90" height="90" fill="white" />{bits.map((active, i) => active && <rect key={i} x={(i % 9) * 10} y={Math.floor(i / 9) * 10} width="9" height="9" fill="#111827" />)}<rect x="0" y="0" width="30" height="30" fill="white" stroke="#111827" strokeWidth="6" /><rect x="60" y="0" width="30" height="30" fill="white" stroke="#111827" strokeWidth="6" /><rect x="0" y="60" width="30" height="30" fill="white" stroke="#111827" strokeWidth="6" /></svg>;
}

function AssetsModule() {
  const [quantity, setQuantity] = useState(12);
  const labels = Array.from({ length: quantity }, (_, i) => ({ code: `CR-${String(i + 1).padStart(4, "0")}`, name: ["Curvadora hidráulica", "Guincho de içamento", "Andaime multidirecional"][i % 3], serial: `S/N ${202600 + i}` }));
  return <div className="space-y-6"><SectionTitle eyebrow="Ativos e rastreabilidade" title="Etiquetas QR para impressão" description="Gere placas em lote para curvadoras, guinchos e andaimes." action={<Button onClick={() => window.print()}>Imprimir etiquetas</Button>} /><Card><CardHeader><div><h3 className="text-lg font-black text-slate-950 dark:text-white">Lote de etiquetas</h3><p className="text-sm text-slate-500">O payload inclui identificador estável e pode ser lido pelo app offline.</p></div><div className="flex items-center gap-2"><label className="text-xs font-bold text-slate-500">Quantidade</label><input type="number" min={1} max={48} value={quantity} onChange={event => setQuantity(Math.max(1, Math.min(48, Number(event.target.value) || 1)))} className="h-10 w-20 rounded-xl border border-slate-200 px-3 text-center font-bold dark:border-slate-700 dark:bg-slate-800 dark:text-white" /></div></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{labels.map(label => <div key={label.code} className="label-card flex items-center gap-3 rounded-xl border-2 border-slate-200 bg-white p-3 dark:border-slate-700"><QrPattern seed={label.code} /><div><p className="text-sm font-black text-slate-950">{label.code}</p><p className="mt-1 text-xs font-bold text-slate-600">{label.name}</p><p className="mt-1 text-[11px] text-slate-500">{label.serial}</p><Badge tone="blue">QR ativo</Badge></div></div>)}</div></CardContent></Card></div>;
}

export default function Dashboard() {
  const [active, setActive] = useState<Module>("overview");
  const [dark, setDark] = useState(false);
  const role = (process.env.NEXT_PUBLIC_USER_ROLE as Role | undefined) ?? "ENGENHEIRO_RESIDENTE";
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);
  const content = useMemo(() => { if (active === "progress") return <ProgressModule />; if (active === "rdo") return <RdoModule role={role} />; if (active === "assets") return <AssetsModule />; return <OverviewModule onRdo={() => setActive("rdo")} />; }, [active, role]);
  const mobileItems: Array<[Module, string]> = [["overview", "Visão"], ["progress", "Avanço"], ["rdo", "RDO"], ["assets", "Ativos"]];
  return <div className="min-h-screen bg-[#f7f8fa] text-slate-950 dark:bg-slate-950 dark:text-white"><div className="flex"><Sidebar active={active} onChange={setActive} role={role} /><div className="min-w-0 flex-1"><Topbar role={role} dark={dark} onToggle={() => setDark(value => !value)} /><div className="flex gap-1 overflow-x-auto border-b border-slate-200 bg-white px-4 py-2 lg:hidden dark:border-slate-800 dark:bg-slate-950">{mobileItems.map(([id, label]) => <button key={id} onClick={() => rolePermissions[id].includes(role) && setActive(id)} className={cn("whitespace-nowrap rounded-lg px-3 py-2 text-xs font-black", active === id ? "bg-slate-950 text-white dark:bg-caramuru-gold dark:text-slate-950" : "text-slate-500")}>{label}</button>)}</div><main className="mx-auto max-w-[1600px] p-5 sm:p-8">{content}</main></div></div></div>;
}
